In [2]:
import numpy as np

In [2]:
arr=np.array([1,2,4])

In [4]:
print(arr)

[1 2 4]


In [7]:
arr1=np.array([[1.0,2.0,4.0],[1.0,9.0,8.0]])

In [8]:
print(arr1)

[[1. 2. 4.]
 [1. 9. 8.]]


In [11]:
arr.ndim

1

In [12]:
arr.dtype

dtype('int32')

In [13]:
arr.itemsize

4

In [15]:
arr1[0,1]

2.0

In [16]:
arr1[0,:]

array([1., 2., 4.])

In [17]:
arr1[:,2]

array([4., 8.])

In [18]:
arr1[0,1:2:1]

array([2.])

In [19]:
arr1[1,2]=0.9
print(arr1)

[[1.  2.  4. ]
 [1.  9.  0.9]]


In [21]:
arr1[:,2]=[1,2]

In [22]:
print(arr1)

[[1. 2. 1.]
 [1. 9. 2.]]


In [24]:
arr3=np.array([[[1,2],[4,5]],[[1,2],[4,7]]])

In [25]:
print(arr3)

[[[1 2]
  [4 5]]

 [[1 2]
  [4 7]]]


In [28]:
arr3[1,1,0]

4

In [30]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [31]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [32]:
np.full((2,2),99) ## any specific number

array([[99, 99],
       [99, 99]])

In [34]:
np.full_like(arr3,4) ## Any other number

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [38]:
## Randon mumber
np.random.rand(4,2)

array([[0.42370814, 0.52704962],
       [0.21111402, 0.68637025],
       [0.60853403, 0.61988208],
       [0.79773351, 0.8633876 ]])

In [42]:
np.random.randint(-1,7,size=(3,3)) ## Randon integer values

array([[ 2,  3,  6],
       [ 2,  2,  5],
       [-1,  5,  0]])

In [43]:
np.identity(6) ## Identity array

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [46]:
r1=np.repeat(arr3,3,axis=0) ## Repeating array

In [47]:
print(r1)

[[[1 2]
  [4 5]]

 [[1 2]
  [4 5]]

 [[1 2]
  [4 5]]

 [[1 2]
  [4 7]]

 [[1 2]
  [4 7]]

 [[1 2]
  [4 7]]]


In [16]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Copy Array

In [64]:
arr1=np.array([1,2,3])
b=arr1.copy()
b[1]=200
print(arr1)
print(b)

[1 2 3]
[  1 200   3]


### Mathematics

In [65]:
arr1+2

array([3, 4, 5])

In [66]:
arr1*2

array([2, 4, 6])

In [67]:
arr1**2

array([1, 4, 9], dtype=int32)

### Linear Algebra

In [3]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [4]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [5]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.min(stats)


1

In [10]:
np.min(stats, axis=1)

array([1, 4])

In [12]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [13]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [14]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])